<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de NumPy

In [2]:
import numpy as np

#### Ejercicio 1 - Crea un array de 1D con los números del 0 al 9.

In [3]:
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


#### Ejercicio 2 - Convierte un array 1D en un array 2D con 2 filas y 5 columnas.

In [4]:
arr2 = arr1.reshape(2,5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Ejercicio 3 - Encuentra los índices de los elementos con valor distinto de 0 en el siguiente array: [0, 2, 0, 3, 0, 4, 0].

In [5]:
arr3 = np.array([0, 2, 0, 3, 0, 4, 0])
arr3 != 0
np.where(arr3 !=0)[0]

array([1, 3, 5], dtype=int64)

#### Ejercicio 4 - Crea un array 3x3 con valores aleatorios entre 0 y 1.

In [6]:
arr4 = np.random.randint(0,2,(3,3))
print(arr4)

[[0 1 1]
 [0 1 1]
 [1 1 1]]


#### Ejercicio 5 - Crea un array de 10 números aleatorios y encuentra el valor máximo y mínimo.

In [7]:
arr5 = np.random.rand(10)
maximum = arr5.max()
minimum = arr5.min()

print(f'Máximo: {maximum:.3f}\nMínimo: {minimum:.3f}')

Máximo: 0.946
Mínimo: 0.042


#### Ejercicio 6 - Crea un array de una dimensión e inviértelo. 

In [8]:
arr6 = np.random.randint(1,10,10)
reversed_arr6 = arr6[::-1]
print(f'Normal: {arr6}')
print(f"Invertido: {reversed_arr6}")

Normal: [3 4 7 2 7 6 1 5 9 6]
Invertido: [6 9 5 1 6 7 2 7 4 3]



#### Ejercicio 6 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Selecciona el primer `15` del array.

- Selecciona todos los elementos del primer array. 

- Selecciona la última fila del último array


In [9]:
arr6_3d = np.random.randint(1,25, (2, 3, 4))
# Solución sin aleatorios
# arr6_3d = np.arange(1,25).reshape(2,3,4)
print(f"Array inicial:\n{arr6_3d}")

arr_pos15 = np.array(np.where(arr6_3d == 15))
if arr_pos15.size == 0:
    print("\nNo hay 15")
else:
    print(f"\nEl 15 se encuentra en: {arr_pos15[:,0]}")

print(f"\nLos elementos del primer array son:\n{arr6_3d[0,:,:]}")
print(f"\nLa última fila del último array es:\n {arr6_3d[1,2]}")

Array inicial:
[[[ 6 18  7  8]
  [10  1 15  1]
  [12 16 24 17]]

 [[ 5 11  8 20]
  [15 22 10  4]
  [12 19 16  6]]]

El 15 se encuentra en: [0 1 2]

Los elementos del primer array son:
[[ 6 18  7  8]
 [10  1 15  1]
 [12 16 24 17]]

La última fila del último array es:
 [12 19 16  6]



#### Ejercicio 7 - Genera un array tridimensional de dimensiones (3, 2, 5) con valores enteros del 1 al 30.

- Selecciona el subarray que contiene los dos primeros elementos de cada fila del primer array.

- Selecciona el subarray que contiene todas las filas de los dos últimos arrays.


In [10]:
arr7 = np.random.randint(1, 31, (3, 2, 5))
# Solución sin aleatorios
# arr7 = np.arange(1,31).reshape(3,2,5)
print(f"Array inicial:\n{arr7}")

print(f'\nSubarray de los dos elementos de cada fila del primer array: \n{arr7[0,:,:2]}')
print(f'\n Subarray que contiene todas las filas de los dos últimos arrays: \n{arr7[-2:,:]}')


Array inicial:
[[[10 22 15 16  1]
  [26 23 18 29  4]]

 [[22 28  7 23  5]
  [ 3 27  3 28 12]]

 [[23 14  9 21  8]
  [ 3  2 26  8  8]]]

Subarray de los dos elementos de cada fila del primer array: 
[[10 22]
 [26 23]]

 Subarray que contiene todas las filas de los dos últimos arrays: 
[[[22 28  7 23  5]
  [ 3 27  3 28 12]]

 [[23 14  9 21  8]
  [ 3  2 26  8  8]]]


#### Ejercicio 8 - Genera un array tridimensional de dimensiones (4, 3, 2) con valores enteros del 1 al 24.

- Cambia todos los elementos de la segunda fila del segundo array por `0`.

- Cambia todos los valores del último array a `-1`.


In [11]:
arr8 = np.random.randint(1,25, (4, 3, 2))
# Solución sin aleatorios
# arr8 = np.arange(1,25).reshape(4,3,2)
print(f"Array inicial:\n{arr8}")
arr8[1,1,:] = 0
print(f"Array modificado con 0:\n{arr8}")
arr8[-1,:,:] = -1
print(f"Array con último array modificado:\n{arr8}")

Array inicial:
[[[20  6]
  [17 21]
  [14  8]]

 [[15 14]
  [22 12]
  [ 7  2]]

 [[ 9 23]
  [23  6]
  [13 24]]

 [[ 8  8]
  [12 21]
  [22 12]]]
Array modificado con 0:
[[[20  6]
  [17 21]
  [14  8]]

 [[15 14]
  [ 0  0]
  [ 7  2]]

 [[ 9 23]
  [23  6]
  [13 24]]

 [[ 8  8]
  [12 21]
  [22 12]]]
Array con último array modificado:
[[[20  6]
  [17 21]
  [14  8]]

 [[15 14]
  [ 0  0]
  [ 7  2]]

 [[ 9 23]
  [23  6]
  [13 24]]

 [[-1 -1]
  [-1 -1]
  [-1 -1]]]



#### Ejercicio 9 - Genera un array tridimensional de dimensiones (2, 4, 3) con valores enteros del -10 al 13.

- Selecciona todos los elementos mayores a `5`.

- Reemplaza todos los elementos negativos por `0`.


In [12]:
arr9 = np.random.randint(-10, 14, (2, 4, 3))
# Solución sin aleatorios
# arr9 = np.arange(-10,14).reshape(2,4,3)
print(f'Array inicial:\n{arr9}')

arr9_gt5 = np.where(arr9 > 5)
print(f'Índices donde es mayor que 5:\n{arr9_gt5}')

arr9[arr9 < 0] =0
print(f'Valores reemplazados:\n{arr9}')

Array inicial:
[[[  9  11  -1]
  [  1  -6  -7]
  [  5   7   5]
  [  0  -1 -10]]

 [[ -3   4   0]
  [ -2   0   9]
  [  0  13   8]
  [  3   1 -10]]]
Índices donde es mayor que 5:
(array([0, 0, 0, 1, 1, 1], dtype=int64), array([0, 0, 2, 1, 2, 2], dtype=int64), array([0, 1, 1, 2, 1, 2], dtype=int64))
Valores reemplazados:
[[[ 9 11  0]
  [ 1  0  0]
  [ 5  7  5]
  [ 0  0  0]]

 [[ 0  4  0]
  [ 0  0  9]
  [ 0 13  8]
  [ 3  1  0]]]


#### Ejercicio 10 - Genera un array tridimensional de dimensiones (3, 3, 3) con valores enteros del 1 al 27.

- Selecciona el subarray del segundo array que contenga solo las dos primeras columnas.

- Selecciona todos los elementos del tercer array que sean mayores que `20`.


In [13]:
arr10 = np.random.randint(1, 28, (3, 3, 3))
# Solución sin aleatorios
# arr10 = np.arange(1,28).reshape(3,3,3)

print(f'Array inicial:\n {arr10}\n')
print(f'Subarray del segundo array que contiene solo las dos primeras columnas\n{arr10[1,:,:2]}')
arr10_gt20_3 = arr10[2,:,:] > 20
print(f'Elementos mayores a 20 en el tercer array:\n{np.where(arr10_gt20_3)}')

Array inicial:
 [[[ 4 17 12]
  [21 27 22]
  [27 17 20]]

 [[20  2 15]
  [26 13 12]
  [ 9  6 22]]

 [[21  3 26]
  [ 6 12 11]
  [20  4  3]]]

Subarray del segundo array que contiene solo las dos primeras columnas
[[20  2]
 [26 13]
 [ 9  6]]
Elementos mayores a 20 en el tercer array:
(array([0, 0], dtype=int64), array([0, 2], dtype=int64))


#### Ejercicio 11 - Crea un array de 10 números aleatorios y reemplaza los valores máximos y mínimos por 0.

In [22]:
arr11 = np.random.randint(1,51,10)
print(f'Array inicial:\n{arr11}')
maximo = arr11.max()
minimo = arr11.min()

arr11[np.array(np.where(arr11 == maximo))] = 0
arr11[np.array(np.where(arr11 == minimo))] = 0

print(f'Array con los números modificados:\n{arr11}')

Array inicial:
[27 29 28 13 41  4 30 24 40 28]
Array con los números modificados:
[27 29 28 13  0  0 30 24 40 28]


#### Ejercicio 12 - Genera un array de 15 números aleatorios enteros entre 1 y 100 y reordénalo en orden ascendente.

In [24]:
arr12 = np.random.randint(1,101, 15)
print(f"Array inicial:\n{arr12}")
print(f"Array reordenado:\n{np.sort(arr12)}")

Array inicial:
[98 93 69 17 93 98 85 55 21 63 14 15 92 77 71]
Array reordenado:
[14 15 17 21 55 63 69 71 77 85 92 93 93 98 98]


#### Ejercicio 11 - Calcula la suma de los elementos a lo largo de las filas y columnas en una matriz 4x4.

In [29]:
arr11 = np.random.randint(1,11,(4,4))
print(f"Matriz 4x4: \n{arr13}")

print(f"Suma de elementos por fila: \n{np.sum(arr11, axis = 0)}")
print(f"Suma de elementos por columna: \n{np.sum(arr11, axis = 1)}")

Matriz 4x4: 
[[ 9  5  2 10]
 [ 3  9  7  2]
 [ 3  5  1  5]
 [10 10  3  1]]
Suma de elementos por fila: 
[30 23 31 34]
Suma de elementos por columna: 
[27 31 30 30]


#### Ejercicio 12 - Crea una matriz de 5x5 con valores en el borde igual a 1 y en el interior igual a 0.

In [37]:
arr12 = np.ones((5,5), dtype=int)
arr12[1:-1,1:-1]=0
print(f'Array 5x5 de 0 y 1: \n{arr12}')

Array 5x5 de 0 y 1: 
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Ejercicio 13 - Calcula la media y la desviación estándar de un array de 10 números aleatorios.

In [75]:
arr13 = np.random.randint(0,100,10)
print(f"Array de números aleatorios: {arr13}")
print(f"Media aritmética de los datos:\n{np.mean(arr13)}")
print(f"Desviación típica de los datos: \n{np.std(arr13):.2f}")

Array de números aleatorios: [ 1 38 73 45 76 78 34 81 67 47]
Media aritmética de los datos:
54.0
Desviación típica de los datos: 
24.32


#### Ejercicio 14 - Genera un array tridimensional de dimensiones (2, 3, 4) con valores enteros del 1 al 24.

- Transpón el array para intercambiar los ejes de la forma (2, 3, 4) a (4, 3, 2).

- Observa cómo cambian las posiciones de los elementos y sus índices después de la transposición. Explica en una celda de markdown que es lo que ha pasado. 


In [89]:
arr14 = np.arange(1,25).reshape(2,3,4)
print(f'Array inicial: \n{arr14}\n')
print(f'Array traspuesto: \n{np.transpose(arr14, (2,1,0))}\n')

Array inicial: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Array traspuesto: 
[[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]



Transposición (2,3,4) --> (4,3,2): Al usar ```np.transpose(arr, axes)``` donde ```axes``` va a ser (2,1,0), ya que cambiamos el eje de las columnas a las matrices (tercera posición de eje, 2 en python, a primera) , mantenemos el eje de las columnas (segunda posición de eje, 1 en python, se mantiene) y cambiamos el eje de las filas a eje de array (primera posición de eje, 0 en python, a tercera).

#### Ejercicio 15 - Genera un array tridimensional de dimensiones (3, 4, 2) con valores enteros del 1 al 24.

- Transpón el array para intercambiar el primer y segundo eje, de manera que la nueva forma del array sea (4, 3, 2).


In [93]:
arr15 = np.arange(1,25).reshape(3,4,2)
print(f"Array inicial: \n{arr15}\n")
print(f"Array traspuesta: \n{np.transpose(arr15, (1,0,2))}")

Array inicial: 
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]

Array traspuesta: 
[[[ 1  2]
  [ 9 10]
  [17 18]]

 [[ 3  4]
  [11 12]
  [19 20]]

 [[ 5  6]
  [13 14]
  [21 22]]

 [[ 7  8]
  [15 16]
  [23 24]]]


#### Ejercicio 16 - Genera un array tridimensional de dimensiones (3, 2, 4) con valores enteros del 1 al 24.

- Realiza una rotación completa de los ejes para convertir la forma original (3, 2, 4) en (4, 3, 2).


In [110]:
arr16 = np.arange(1,25).reshape(3,2,4)
print(f"Array inicial: \n{arr16}\n")
print(f"Array rotado: \n{np.transpose(arr16, (2,0,1))}")

Array inicial: 
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]

Array rotado: 
[[[ 1  5]
  [ 9 13]
  [17 21]]

 [[ 2  6]
  [10 14]
  [18 22]]

 [[ 3  7]
  [11 15]
  [19 23]]

 [[ 4  8]
  [12 16]
  [20 24]]]


#### Ejercicio 17 - Manipulación de Arrays en 3D

- Crea un array tridimensional con dimensiones (3, 4, 5) cuyos elementos sean números enteros aleatorios entre -10 y 10.

- Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Luego, reemplaza los valores de la matriz vacía basada en los valores del primer array bajo las siguientes condiciones:

   - Si el valor es igual a la mediana, se reemplaza por `"M"`.

   - Si el valor es mayor que la mediana, se reemplaza por `"X"`.

   - Si el valor es menor que la mediana, se reemplaza por `"Y"`.

   - Si el valor es igual al máximo, se reemplaza por `"MAX"`.

   - Si el valor es igual al mínimo, se reemplaza por `"MIN"`.


In [146]:
arr17 = np.random.randint(-10, 10, (3,4,5))
print(f"Array inicial: \n{arr17}")
arr17_empty = np.empty((3,4,5), dtype=object)
median = int(np.median(arr17))
maximo = np.max(arr17)
minimo = np.min(arr17)

median_eq = arr17 == median
median_gt = arr17 > median
median_lt = arr17 < median
max_cond = arr17 == maximo
min_cond = arr17 == minimo


arr17_empty[(median_eq)] = "M"
arr17_empty[(median_gt)] = "X"
arr17_empty[median_lt] = "Y"
arr17_empty[max_cond] = "MAX"
arr17_empty[min_cond] = "MIN"

print(f"\nArray vacío actualizado: \n{arr17_empty}")

Array inicial: 
[[[  5   2   2 -10  -7]
  [  6  -1  -6   3  -3]
  [  8  -6  -7   2   3]
  [ -5  -8   1  -8  -7]]

 [[-10   9  -6  -3  -9]
  [  7  -6  -2   0   3]
  [ -7   9   5  -5 -10]
  [  0  -1   4   6  -4]]

 [[  8   3  -9   8   2]
  [ -3   6  -7   7   8]
  [  4   0   6  -6  -7]
  [ -6   4  -4   5  -9]]]

Array vacío actualizado: 
[[['X' 'X' 'X' 'MIN' 'Y']
  ['X' 'Y' 'Y' 'X' 'Y']
  ['X' 'Y' 'Y' 'X' 'X']
  ['Y' 'Y' 'X' 'Y' 'Y']]

 [['MIN' 'MAX' 'Y' 'Y' 'Y']
  ['X' 'Y' 'Y' 'M' 'X']
  ['Y' 'MAX' 'X' 'Y' 'MIN']
  ['M' 'Y' 'X' 'X' 'Y']]

 [['X' 'X' 'Y' 'X' 'X']
  ['Y' 'X' 'Y' 'X' 'X']
  ['X' 'M' 'X' 'Y' 'Y']
  ['Y' 'X' 'Y' 'X' 'Y']]]


#### Ejercicio 18 - Verificación de Filas y Columnas Iguales

Crea un array bidimensional de dimensiones 4x4, escribe un código para determinar si alguna fila es exactamente igual a alguna columna.

**Reglas:**

- No puedes usar funciones predefinidas de NumPy para comparar filas y columnas (`np.array_equal`, etc.).

- Debes resolverlo con estructuras básicas de Python (bucles, condicionales, etc.).

- Debes revisar si hay al menos una fila que coincida exactamente con alguna columna.

**Pistas**:

- Puedes recorrer cada fila y cada columna de la matriz usando bucles.

- Para comparar una fila con una columna, puedes hacerlo elemento por elemento.

In [182]:
arr18 = np.array([[[2, 0, 0, 0],
                   [2, 2, 1, 2],
                   [1, 1, 2, 1],
                   [1, 0, 2, 1]],

                  [[2, 0, 1, 1],
                   [1, 2, 2, 2],
                   [2, 1, 2, 2],
                   [2, 0, 2, 1]]])

# def check_equal(arr18):
print(f'Array inicial: \n{arr18}\n')
a, r, c = arr18.shape

def check_fila_eq_columna(array):
    for i in range(a):
        for j in range(r):
            # Filas
            fila = array[i,j,:]
            for k in range(c):
                # Columnas
                columna = array[i,:,k]
                # print(f"Fila: {fila}\nColumna: {columna}\n")
                if all(fila == columna):
                    return f"Hay una coincidencia:\n{fila}"
    return f"No hay ninguna coincidencia..."
                
print(check_fila_eq_columna(arr18))

Array inicial: 
[[[2 0 0 0]
  [2 2 1 2]
  [1 1 2 1]
  [1 0 2 1]]

 [[2 0 1 1]
  [1 2 2 2]
  [2 1 2 2]
  [2 0 2 1]]]

Hay una coincidencia:
[1 2 2 2]
